In [2]:
import pandas as pd

In [8]:
df_processed_data = pd.read_csv('./data/processed_data.csv', index_col=[0])
df_new_data = pd.read_csv('./data/new_data.csv', index_col=[0])

In [9]:
df_processed_data

,new_house_price,Is_samambaia_norte,n_rooms,has_condominium,value_condominium,has_parking,n_parking,house_size,house_hyperlink
0,152000.0,0,1,1,329.0,0,0,38.0,https://df.olx.com.br/distrito-federal-e-regia...
1,408000.0,0,2,1,432.0,1,1,65.0,https://df.olx.com.br/distrito-federal-e-regia...
2,145000.0,1,2,1,10.0,0,0,63.0,https://df.olx.com.br/distrito-federal-e-regia...
3,190000.0,0,2,1,350.0,1,1,55.0,https://df.olx.com.br/distrito-federal-e-regia...
4,290000.0,1,2,0,0.0,1,1,105.0,https://df.olx.com.br/distrito-federal-e-regia...
...,...,...,...,...,...,...,...,...,...
2921,168000.0,1,2,1,0.0,0,0,33.0,https://df.olx.com.br/distrito-federal-e-regia...
2922,168000.0,1,2,1,0.0,1,1,33.0,https://df.olx.com.br/distrito-federal-e-regia...
2923,168000.0,1,2,1,0.0,1,1,33.0,https://df.olx.com.br/distrito-federal-e-regia...
2924,212060.0,0,2,1,0.0,1,1,42.0,https://df.olx.com.br/distrito-federal-e-regia...
2925,212000.0,1,2,1,0.0,0,0,33.0,https://df.olx.com.br/distrito-federal-e-regia...

In [10]:
df_new_data

     house_category n_bathrooms         CEP                    Logradouro
0      Apartamentos           1  72302705.0  QR 116 Conjunto 4-A ComÃ©rcio
1      Apartamentos           2  72300533.0         Quadra 301 Conjunto 2
2      Apartamentos           1  72316080.0                        QR 204
3      Apartamentos           1  72304051.0             QN 120 Conjunto 1
4             Casas           1  72318030.0            QR 402 Conjunto 29
...             ...         ...         ...                           ...
2921   Apartamentos           1  72321000.0                        QR 407
2922   Apartamentos           1  72321000.0                        QR 407
2923   Apartamentos           1  72321000.0                        QR 407
2924            NaN         NaN         NaN                           NaN
2925   Apartamentos           1  72321003.0             QR 407 Conjunto 3

[2926 rows x 4 columns]

In [11]:
df_ = pd.concat([df_processed_data, df_new_data], axis=1)

In [12]:
df_

,new_house_price,Is_samambaia_norte,n_rooms,has_condominium,value_condominium,has_parking,n_parking,house_size,house_hyperlink,house_category,n_bathrooms,CEP,Logradouro
0,152000.0,0,1,1,329.0,0,0,38.0,https://df.olx.com.br/distrito-federal-e-regia...,Apartamentos,1,72302705.0,QR 116 Conjunto 4-A ComÃ©rcio
1,408000.0,0,2,1,432.0,1,1,65.0,https://df.olx.com.br/distrito-federal-e-regia...,Apartamentos,2,72300533.0,Quadra 301 Conjunto 2
2,145000.0,1,2,1,10.0,0,0,63.0,https://df.olx.com.br/distrito-federal-e-regia...,Apartamentos,1,72316080.0,QR 204
3,190000.0,0,2,1,350.0,1,1,55.0,https://df.olx.com.br/distrito-federal-e-regia...,Apartamentos,1,72304051.0,QN 120 Conjunto 1
4,290000.0,1,2,0,0.0,1,1,105.0,https://df.olx.com.br/distrito-federal-e-regia...,Casas,1,72318030.0,QR 402 Conjunto 29
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2921,168000.0,1,2,1,0.0,0,0,33.0,https://df.olx.com.br/distrito-federal-e-regia...,Apartamentos,1,72321000.0,QR 407
2922,168000.0,1,2,1,0.0,1,1,33.0,https://df.olx.com.br/distrito-federal-e-regia...,Apartamentos,1,72321000.0,QR 407
2923,168000.0,1,2,1,0.0,1,1,33.0,https://df.olx.com.br/distrito-federal-e-regia...,Apartamentos,1,72321000.0,QR 407
2924,212060.0,0,2,1,0.0,1,1,42.0,https://df.olx.com.br/distrito-federal-e-regia...,NaN,NaN,NaN,NaN
2925,212000.0,1,2,1,0.0,0,0,33.0,https://df.olx.com.br/distrito-federal-e-regia...,Apartamentos,1,72321003.0,QR 407 Conjunto 3